### ISSUE TITLE
关于接口调用

### ISSUE THREAD

**Issue by SuperVBird** [FlanNep/PicaComic-Api#5]
请问这个是实例化 PicaLoginApi 这个类在构造里写上用户名密码，然后获取登录token,将token放入header,实例化各个功能类，初始化时带上设置好的header吗，我在mian方法里试了下登录，捕获异常是 PicaException ，输入正确的密码和错误的，都没啥反应，不抛异常也不会输出结果，这个项目应该不需要容器部署吧

```
public static void main(String[] args) {
         String username = "********";
         String password = "*********";
       //构建登陆api
        PicaLoginApi lapi = new PicaLoginApi(username, password);
        //获取服务端返回的登陆结果
        try {
            PicaLoginResult loginResult = lapi.login();
            String token=loginResult.getToken();
            System.out.println(token);
         } catch (PicaException e) {
            e.printStackTrace();
        } catch(Exception e){           
        }
    }
```

**Comment by SuperVBird** [comment]
![2X`{CKP5UN(~U I}0Z C98F](https://user-images.githubusercontent.com/40413302/56458502-f9a5c100-63b9-11e9-99dc-49e39839dc91.png)
我输入了用户名和密码，最后debug在查看发送的url里面时，用户名和密码就变为“”了 ，tag也是null

**Comment by FlanNep** [comment]
抛出的PicaException没有有printStackTrace的内容吗？我这边测试是正常的
