### ISSUE TITLE
无法获取到高质量的图片(含临时解决方法)

### ISSUE THREAD

**Issue by leveychen** [FlanNep/PicaComic-Api#7]
[https://github.com/FlanNep/PicaComic-Api/blob/master/src/main/java/com/flannep/picacomic/api/resources/Media.java](url)

根据media构造的图片链接已经失效了。只能请求到小图。

**Comment by FlanNep** [comment]
似乎是之前哔咔更换图片服务器导致的，这个问题在处理了

**Comment by FlanNep** [comment]
问题已经查明，哔咔新版本增加了一个请求头``image-quality``

临时的解决方法，在初始化BookApi的构造函数提供的header中，添加一个自定义header，key=image-quality，value=original
样例:
```
header.setCustomHeader("image-quality", "original");
PicaBookApi picaBookApi = new PicaBookApi(header);
```

将会尽快在新版本中增加对图片质量的支持

**Comment by leveychen** [comment]
直接添加到标准header里面亦可。不会影响其他接口。
