### ISSUE TITLE
Testing LoginApi Error

### ISSUE THREAD

**Issue by BohanRen** [FlanNep/PicaComic-Api#8]
### 我测试你的登录部分的时候，用Postman模拟了一下登录的请求，但是返回了这样的错误

![](https://i.loli.net/2019/06/29/5d1766aa2251c53975.png)

### 我在想是不是 `api-key` 失效了？
![QQ截图20190629212229](https://user-images.githubusercontent.com/23572936/60384764-95d3fe80-9ab4-11e9-8448-8e1ac779377d.png)

**Comment by FlanNep** [comment]
账户和密码要以json形式放在post body里

例:

{"email":"example@test.com","password":"12345678"}

**Comment by BohanRen** [comment]
OK,回头试一下
